version: '3.8'

services:
  pg-backup:
    image: ghcr.io/dimantchick/pg-backup:latest
    container_name: pg-backup
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_REGION=${S3_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DAYS_TO_KEEP=${DAYS_TO_KEEP:-30}
      - TZ=${TZ:-Europe/Moscow}
      - CRON_SCHEDULE=2 0 * * *
      # Дополнительные настройки для надежности
    healthcheck:
      test: [ "CMD-SHELL", "pgrep crond || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "10m"
        max-file: "3"